[package]
name = "aira-cli"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
path = "src/main.rs"
name = "aira"
doc = false

[dependencies]
aira.workspace = true

anyhow = "1"
clap = { version = "4", features = ["cargo", "wrap_help"] }
