name: ci
on:
  pull_request: {}
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.ref == 'refs/heads/main' }}
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack,cargo-nextest,just
    - name: cargo check
      run: just check
    - name: cargo test
      run: just test

